# Generated by Django 2.1.5 on 2023-11-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingIFC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_bag_id', models.CharField(max_length=255, unique=True)),
                ('ifc_file', models.FileField(upload_to='ifc_files/')),
            ],
        ),
    ]
