# Generated by Django 4.2.7 on 2023-11-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifcupload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildingifc',
            name='id',
        ),
        migrations.AlterField(
            model_name='buildingifc',
            name='ref_bag_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
