# Generated by Django 2.1.5 on 2023-10-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurtainWall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('global_id', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('tag', models.CharField(max_length=200)),
                ('length', models.FloatField()),
                ('area', models.FloatField()),
            ],
        ),
    ]
